# Generated by Django 5.1.6 on 2025-04-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='core_values',
        ),
        migrations.DeleteModel(
            name='CoreValue',
        ),
    ]
