# Generated by Django 5.1.6 on 2025-04-19 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_teammember_core_values_delete_corevalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentselection',
            name='step',
        ),
        migrations.RemoveField(
            model_name='studentselection',
            name='student',
        ),
        migrations.DeleteModel(
            name='EventAttendance',
        ),
        migrations.DeleteModel(
            name='SelectionProcedure',
        ),
        migrations.DeleteModel(
            name='StudentSelection',
        ),
    ]
