# Generated by Django 5.1.6 on 2025-02-27 21:19

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_learningschedule_module_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('birth_date', models.DateField()),
                ('zip_code', models.CharField(max_length=20)),
                ('country_of_birth', django_countries.fields.CountryField(max_length=2)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('register_number', models.CharField(blank=True, max_length=50, null=True)),
                ('diploma_level', models.CharField(choices=[('PhD', 'PhD'), ('Master', 'Master'), ('Bachelor', 'Bachelor'), ('Secondary School', 'Secondary School'), ('No Option', 'No Option')], max_length=20)),
                ('job_status', models.CharField(max_length=50)),
                ('motivation', models.TextField()),
                ('future_goals', models.TextField()),
                ('proudest_moment', models.TextField()),
                ('english_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('how_heard', models.CharField(max_length=100)),
                ('referral_person', models.CharField(blank=True, max_length=100, null=True)),
                ('has_laptop', models.BooleanField()),
            ],
        ),
    ]
