# Generated by Django 5.2.6 on 2025-09-24 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_partner_options_alter_partner_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={'ordering': ['-graduation_year', 'user__username']},
        ),
        migrations.AlterField(
            model_name='alumni',
            name='graduation_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
