# Generated by Django 5.1.6 on 2025-09-30 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_alumni_options_alter_alumni_graduation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the event (flyer, poster, banner)', null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='event',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='events', to='courses.partner'),
        ),
    ]
