# Generated by Django 5.1.6 on 2025-03-14 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_contactus_partner_selectionprocedure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='courses.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='partners',
            field=models.ManyToManyField(related_name='courses', to='courses.partner'),
        ),
        migrations.AddField(
            model_name='event',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
        migrations.AddField(
            model_name='event',
            name='partners',
            field=models.ManyToManyField(related_name='events', to='courses.partner'),
        ),
        migrations.AddField(
            model_name='learningschedule',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='alumni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.alumni'),
        ),
        migrations.AddField(
            model_name='review',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='courses.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='schedules',
            field=models.ManyToManyField(related_name='students', to='courses.learningschedule'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='core_values',
            field=models.ManyToManyField(related_name='team_members', to='courses.corevalue'),
        ),
        migrations.AlterField(
            model_name='review',
            name='about_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.aboutus'),
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='courses.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to='courses.student')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Instructor', 'Instructor'), ('Alumni', 'Alumni')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.selectionprocedure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_steps', to='courses.student')),
            ],
        ),
    ]
