# Generated by Django 5.1.6 on 2025-10-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_aboutus_options_aboutus_image"),
    ]
