# Generated by Django 5.1.6 on 2025-10-02 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_corevalue_options_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['name']},
        ),
    ]
