# Generated by Django 5.2.6 on 2025-11-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_courseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, help_text='Training end date', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='registration_deadline',
            field=models.DateField(blank=True, help_text='Last date to register', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='selection_date',
            field=models.DateField(blank=True, help_text='Date when selections are announced', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, help_text='Training start date', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='topics_covered',
            field=models.TextField(blank=True, help_text='Topics/content covered in this course', null=True),
        ),
    ]
