# Generated by Django 5.2.6 on 2025-11-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_end_date_course_registration_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Professional biography', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, help_text='Professional title (e.g., Data Science Instructor)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL', null=True),
        ),
    ]
