# Generated by Django 5.1.14 on 2026-06-10 22:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_end_date_course_registration_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='graduation_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2027)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Quantitative Methods', 'Quantitative Methods'), ('Qualitative Methods', 'Qualitative Methods'), ('Spatial Analysis', 'Spatial Analysis'), ('Research Productivity', 'Research Productivity')], max_length=50),
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('session_date', models.DateTimeField()),
                ('discord_link', models.URLField(help_text='Discord channel or event link for this session')),
                ('recording_url', models.URLField(blank=True, help_text='Link to recording after session ends', null=True)),
                ('notes', models.TextField(blank=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='courses.module')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='courses.learningschedule')),
            ],
            options={
                'ordering': ['session_date'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField(blank=True, help_text='Link to your R script or GitHub repository')),
                ('notes', models.TextField(blank=True, help_text='Any notes or questions for your instructor')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Returned', 'Returned'), ('Passed', 'Passed')], default='Submitted', max_length=20)),
                ('instructor_feedback', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.student')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('module', 'student')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text="Student's personal notes for this lesson")),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='courses.student')),
            ],
            options={
                'ordering': ['lesson__order'],
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
