# Generated by Django 5.2.6 on 2025-11-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_profile_bio_profile_email_profile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='additional_materials',
            field=models.FileField(blank=True, help_text='Additional materials (PDF, CSV, etc.)', null=True, upload_to='course_materials/'),
        ),
        migrations.AddField(
            model_name='course',
            name='discord_community',
            field=models.URLField(blank=True, help_text='Discord community invite link', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='github_repository',
            field=models.URLField(blank=True, help_text='GitHub repository URL', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='video_content',
            field=models.FileField(blank=True, help_text='Course video file', null=True, upload_to='course_videos/'),
        ),
    ]
