# Generated by Django 5.2.6 on 2025-11-21 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_additional_materials_course_discord_community_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Material title/name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Brief description', null=True)),
                ('material_type', models.CharField(choices=[('video', 'Video'), ('document', 'Document'), ('spreadsheet', 'Spreadsheet'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(help_text='Upload file', upload_to='course_materials/%Y/%m/')),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Material',
                'verbose_name_plural': 'Course Materials',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
