# Generated by Django 5.1.14 on 2025-11-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_coursematerial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursematerial',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the material', null=True),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(help_text='Upload file (video, PDF, CSV, etc.)', upload_to='course_materials/%Y/%m/'),
        ),
    ]
