# Generated by Django 5.1.6 on 2025-12-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_corevalue_options_alter_coursematerial_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        # Constraint already exists from previous migration, no need to add again
    ]
