# Generated by Django 5.1.6 on 2025-12-10 21:02

from django.db import migrations, models


def add_constraint_if_not_exists(apps, schema_editor):
    """Add constraint only if it doesn't already exist"""
    with schema_editor.connection.cursor() as cursor:
        # Check if constraint exists
        cursor.execute("""
            SELECT 1 FROM pg_constraint 
            WHERE conname = 'unique_corevalue_title_per_aboutus'
        """)
        
        if not cursor.fetchone():
            # Constraint doesn't exist, create it
            cursor.execute("""
                ALTER TABLE courses_corevalue 
                ADD CONSTRAINT unique_corevalue_title_per_aboutus 
                UNIQUE (about_us_id, title)
            """)


def remove_constraint_if_exists(apps, schema_editor):
    """Remove constraint if it exists (for rollback)"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE courses_corevalue 
            DROP CONSTRAINT IF EXISTS unique_corevalue_title_per_aboutus
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_alter_event_options_and_more'),
    ]

    operations = [
        migrations.RunPython(add_constraint_if_not_exists, remove_constraint_if_exists),
    ]
