# Generated by Django 5.1.6 on 2025-12-10 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_corevalue_unique_corevalue_title_per_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(help_text='Course category', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.coursecategory'),
        ),
        # Constraint already exists, no need to add again
    ]
