# Generated by Django 5.1.6 on 2025-12-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_change_category_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Instructor', 'Instructor'), ('Alumni', 'Alumni'), ('Admin', 'Admin')], max_length=20),
        ),
        # Constraint already exists, no need to add again
    ]
