# Generated by Django 5.1.14 on 2026-06-12 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_drop_orphaned_tables'),
        ('courses', '0029_add_admin_role'),
    ]

    operations = [
    ]
