# Generated by Django 5.1.14 on 2026-06-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_merge_0017_drop_orphaned_tables_0029_add_admin_role'),
    ]

    operations = [
        # These tables/fields were already physically dropped by 0017_drop_orphaned_tables
        # (via raw SQL DROP TABLE IF EXISTS).  We use SeparateDatabaseAndState so Django
        # updates its migration state without attempting any DDL that would fail.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='CourseCategory'),
                migrations.RemoveField(model_name='coursematerial', name='course'),
                migrations.RemoveField(model_name='coursematerial', name='uploaded_by'),
                migrations.RemoveField(model_name='course', name='additional_materials'),
                migrations.RemoveField(model_name='course', name='discord_community'),
                migrations.RemoveField(model_name='course', name='github_repository'),
                migrations.RemoveField(model_name='course', name='video_content'),
                migrations.RemoveField(model_name='profile', name='bio'),
                migrations.RemoveField(model_name='profile', name='email'),
                migrations.RemoveField(model_name='profile', name='linkedin_url'),
                migrations.RemoveField(model_name='profile', name='profile_picture'),
                migrations.RemoveField(model_name='profile', name='title'),
                migrations.RemoveField(model_name='profile', name='twitter_url'),
                migrations.DeleteModel(name='CourseMaterial'),
            ],
            database_operations=[],
        ),

        # Safe DDL — these tables exist and we are only adding indexes / updating choices.
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email_verification_token',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Instructor', 'Instructor'), ('Alumni', 'Alumni')], max_length=20),
        ),
        # Constraint already exists in the DB — update state only.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddConstraint(
                    model_name='corevalue',
                    constraint=models.UniqueConstraint(fields=('about_us', 'title'), name='unique_corevalue_title_per_aboutus'),
                ),
            ],
            database_operations=[],
        ),
    ]

