# Generated by Django 5.1.14 on 2026-06-13 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_remove_contactus_email_unique'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('schedule', 'order')},
        ),
    ]
