# Generated by Django 5.1.14 on 2026-06-15 22:48

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_add_discountcode_payment_discount_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='future_goals',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='how_heard',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='motivation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='proudest_moment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='zip_code',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
    ]
