# Generated by Django 5.1.14 on 2026-06-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_simplify_student_optional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='software_tools',
            field=models.TextField(blank=True, default='', help_text='List of software and languages covered'),
        ),
    ]
