# Generated by Django 5.1.14 on 2026-09-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_event_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTAClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cta_name', models.CharField(choices=[('apply_hero', 'Apply — Hero Section'), ('view_programmes', 'View Programmes — Hero'), ('apply_final_cta', 'Apply — Final CTA Section'), ('ask_question', 'Ask a Question — Final CTA'), ('view_all_programmes', 'View All Programmes'), ('register_event', 'Register for Event'), ('contact_us', 'Contact Us'), ('login', 'Login'), ('register', 'Register / Sign Up'), ('apply_course', 'Apply — Course Page'), ('other', 'Other')], db_index=True, max_length=50)),
                ('page', models.CharField(help_text='Page path where click occurred', max_length=255)),
                ('session_id', models.CharField(blank=True, help_text='Anonymous session identifier', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
